config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get '/u/:id', to: 'users#profile', as: 'user'

  resources :posts do
    resources :comments
  end

  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 150 }
  validates :body, presence: true, length: { minimum: 10, maximum: 1000 }
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_noticed_notifications model_name: 'Notification'
  has_many :notificatios, through: :user, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  before_action :correct_user, only: %i[edit update destroy]
  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.order(created_at: :desc)

    mark_notifications_as_read
  end

  # GET /posts/new
  def new
    # @post = Post.new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    # @post = Post.new(post_params)
    # @post.user = current_user
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    # don't redirect just display message
    redirect_to posts_path, notice: "You are not authorized to make changes" if @post.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :body, :user_id)
    end

    def mark_notifications_as_read
      if current_user
        notifications_to_mark_as_read = @post.notifications_as_post.where(recipient: current_user)
        notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<form>
  <div class="form-group">
    <%= form.text_field :title, placeholder: "Title", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.text_field :description, placeholder: "Short description", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.text_area :body, placeholder: "Your story goes here", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.number_field :user_id, id: :post_user_id, class: "form-control", value: current_user.id, type: :hidden %>

  </div>

<br>

  <%= form.submit class: "btn btn-primary" %>
  <%= link_to "Back to posts", posts_path, class: "btn btn-secondary" %>

</form>

<% end %>

app/views/posts/_navbar_logic.html.erb
  <li class="nav-item">
    <%= link_to "Posts", posts_path, class:"nav-link" %>
  </li>
<% if current_user %>
  <li class="nav-item">
    <%= link_to "New post", new_post_path, class:"nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "About me", user_path(current_user), class:"nav-link" %>
  </li>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <h2><%= post.title %></h2>
  </p>

  <p>
    <h3><%= post.description %></h2>
  </p>

  <p>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<div class="container">

  <h1>Editing post</h1>

  <%= render "form", post: @post %>

</div>

<br>

app/views/posts/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
  <h1>All Posts</h1>
</div>

<% if notice %>
<p style="color: green"><%= notice %></p>
<% end %>

<div class="container">
  <div id="posts">

    <div class="row">
      <% @posts.each do |post| %>
          <div class="col-sm-6">
              <div class="card">
                <div class="card-body">
                  <%# make clickable cards to direct to show page %>
                  <h5 class="card-title"><%= link_to "#{post.title.upcase}", post_path(post) %></h5>
                  <div class="info">
                    <p class="card-text">Posted by: <%= link_to user_name(post), user_path(post.user) %> <%= time_ago_in_words(post.created_at) %> ago</p>
                    <p class="card-views">Views: <strong><%= post.views %></strong></p>
                  </div>
                  <hr>
                  <p class="card-text"> <%= "#{post.description.capitalize}" %></p>
                </div>
              </div>
          </div>
      <% end %>
    </div>

  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New post</h1>

  <br>

  <%= render "form", post: @post %>
</div>

app/views/posts/show.html.erb
<% if notice %>
   <p style="color: green"><%= notice %></p>
<% end %>

<div class="container">

  <div class="card text-center show-card">

    <div class="show-card-header show-card-body">
      <h2 class= "card-title" > <%= @post.title.upcase %> </h2>
      <%# code for user name extraction from email is in app/helpers/application_helper %>
      <div class="author-views-text">
        <p class="card-text-element"> Posted by: <%= link_to user_name(@post), user_path(@post.user) %></p>
        <p class="card-text-element"> Views: <strong><%= @post.views %></strong> </p>
      </div>
    </div>

    <hr>

    <div class="show-card-body">

      <p class="show-card-text"> <%= @post.body.capitalize %> </p>
    </div>

    <div class="btn-group">
      <%# Fix these damn buttons %>
      <% if @post.user == current_user && user_signed_in? %>
      <%= link_to "Edit post", edit_post_path(@post), class: "btn btn-primary btn-sm mr-2" %>
      <%= link_to "Back to posts", posts_path, class: "btn btn-secondary btn-sm mr-2" %>
      <%= button_to "Delete post", @post, method: :delete, data: { turbo_confirm: "Are you sure you want to delete your post?" }, class: "btn btn-danger btn-sm" %>
      <% else %>
      <%= link_to "Back to posts", posts_path, class: "btn btn-secondary btn-sm" %>
      <% end %>
    </div>

    <div class="card-footer text-muted">
      <%# add date when post created %>
      <%= @post.created_at.strftime("%d %B %Y, %l:%M%P") %>
      <%# add which user created the post %>
    </div>

  </div>



  <div>
    <% if user_signed_in? %>
      <%= render 'comments/form', post: @post, comment: @post.comments.build, submit_label: "Reply" %>
    <h4 class="stubborn-comment-text">Comments</h4>
    <hr>
      <% @comments.each do |comment| %>
      <br>

    <div class="comment-body">
      <%= render 'comments/comment', post: @post, comment: comment %>
    </div>
    <% end %>

  </div>
  <% else %>

    <div class="container card ">
      <h2 class="comment-login-header">You are not signed in</h2>
      <p class="comment-login-text">Please <%= link_to "Login", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %> to be able to comment</p>
    </div>
      <h4>Comments</h4>
      <hr>
      <% @comments.each do |comment| %>
      <br>

    <div class="comment-body">
      <%= render 'comments/comment', post: @post, comment: comment %>
    </div>
    <% end %>

  <% end %>


  </div>


</div>
<br>